### ISSUE TITLE
ChanServ Rejoin after Freeze..

### ISSUE THREAD

**Issue by selangor** [XthemeOrg/Xtheme#15] opened 2015-06-21 14:52 UTC
Hello..i have issue..
Chanserv rejoin after freeze..
If user join.. chanserv rejoin..

***GLOBOPS: From services.int: selangor froze the channel #A (Take Over Issue).
Join: ChanServ [services.int]
Mode: [+o ChanServ] by *.int
-ChanServ-: #A is now frozen.
Mode: [-o A] by ChanServ
Part: ChanServ [ChanServ@services.int] [Leaving]
Part: A [A@-vk7.l33.1.103.IP]
Join: A [-vk7.l33.1.103.IP]
Join: ChanServ [services.int]
Mode: [+o ChanServ] by *.int
Part: ChanServ [ChanServ@services.int] [Leaving]
Join: Rawang [-vk8.l33.1.113.IP]
Join: ChanServ [services.int]
Mode: [+o ChanServ] by *.int
Part: ChanServ [ChanServ@services.int] [Leaving]
Join: Guest47955 [-vk7.l36.1.133.IP]
Join: ChanServ [services.int]
Mode: [+o ChanServ] by *.int
Part: ChanServ [ChanServ@services.int] [Leaving]

**Comment by siniStar7boy** [comment] 2015-06-21 16:01
@selangor If I am understanding properly, you are saying that ChanServ rejoins the channel after it empties and then is re-created by a user joining. (while frozen)    

ChanServ is supposed to rejoin (if the channel is still frozen) when the channel is empty and then re-created by another user to ensure that nobody is able to gain op status.  
When the channel is unfrozen, ChanServ will leave (or stay if GUARD is set)

**Comment by selangor** [comment] 2015-06-21 20:17
Oh.. thanks @siniStar7boy

**Comment by siniStar7boy** [comment] 2015-06-22 15:58
(Not sure if this was re-opened accidentally?) Functionality is working as intended - so I am closing this issue.

**Closed by siniStar7boy** 2015-06-22 15:58 UTC
