### ISSUE TITLE
services database missing +e for channel founder

### ISSUE THREAD

**Issue by Casey952** [XthemeOrg/Xtheme#38] opened 2016-01-24 23:48 UTC
The services database services.db does not have +e for the channel founder and does not say Founder as the flags name and access list says Founder as < Custom >

flags #channel displays Founder as (#channel) [modified ...]
access #channel list as < Custom >

xtheme.conf flags for founder: founder = "+AFORaefhioqrstv";
services.db: +AFORfiorstv
(using mixin no halfops protect owner)

AOP and SOP displays it as AOP and SOP in flags and access list.

When you take out +e for Founder in xtheme.conf, flags and access list displays it correctly as Founder as the name.

**Comment by siniStar7boy** [comment] 2016-01-25 01:52
Add the ``+e`` flag to the founders' affected, or remove the ``e`` from your ChanServ Founder template in xtheme.conf.

Xtheme __does__ save the e flag in the db.  _(More than likely the users in the db you are speaking of do not have the ``+e`` flag)_  

**Closing this issue** _since this is not a bug_.

**Comment by Casey952** [comment] 2016-01-25 02:31
When you register a channel, the founder does not automatically get +e when it is in xtheme.conf and that AOP and SOP both get +e

thinking it could perhaps be due to a module being loaded or not loaded.

I have xop and limitflags loaded.
disabled halfops protect owner.

and running Charybdis.

limitflags I enabled and have got limitflags set for the default flags for new channels, that SOPs can add SOPs and that limitflags prevents that.

xop enabled that you can do xop #channel add nick.

I did have mixins loaded for no halfops protect owner and have disabled them all #.

**Comment by Casey952** [comment] 2016-01-25 03:09
Another thought

the link between xtheme.conf founder templates and services.db might not be forwarding +e to the database.

**Comment by Casey952** [comment] 2016-01-25 03:16
since aop and sop both get +e

and when you register a channel, the founder does not automatically get +e from the founder templates in xtheme.conf

the link between xtheme.conf founder templates and services.db might not be forwarding +e to the database.

or perhaps due to a module being loaded or not loaded.

running Charybdis.

**Comment by siniStar7boy** [comment] 2016-01-25 04:53
Thanks for the additional information.  I will look further into the issue..

**Closed** 2016-01-26 04:08 UTC
Labels: invalid

**Comment by siniStar7boy** [comment] 2016-01-26 04:14
@Casey952 Be sure to remove ``+ahq`` from the default Founder flags in the ChanServ block of the Xtheme conf if you are using **Charybdis** and **above mentioned modules**.  _(Otherwise you will continue to get the `<Custom>` response from ChanServ ``ACCESS LIST``)_

**Comment by Casey952** [comment] 2016-01-26 21:39
When you do not have protect halfops owner loaded in ChanServ, it does not use the +ahq flags from the ChanServ templates block in xtheme.conf.

I use the default templates flags in xtheme.conf but have taken out A for VOP

		vop = "+AV";
		hop = "+AHehitrv";
		aop = "+AOehiortv";
		sop = "+AOaefhiorstv";

		founder = "+AFORaefhioqrstv";


/msg ChanServ templates

-ChanServ- Name                 Flags
-ChanServ- -------------------- -----
-ChanServ- AOP                  +AOeiorv
-ChanServ- FOUNDER              +AFORefiorstv
-ChanServ- HOP                  +Aeirv
-ChanServ- SOP                  +AOefiorstv
-ChanServ- VOP                  +V
-ChanServ- -------------------- -----
-ChanServ- End of network wide template list.

/msg ChanServ templates ignores +ahq when protect halfops owner is not loaded.

The display name shows correctly as AOP and SOP for AOP and SOP from xtheme.conf templates with +ahq for /msg ChanServ flags #channel and /msg ChanServ access #channel list

I guess it should be fine if you do have +ahq or without +ahq in the templates in xtheme.conf

Can services.db be made to automatically add +e exempt if it doesn't with the fix for all channel founders in services.db, or do we need to add +e by hand in services.db for all channel founders and be right for new channels that they will automatically get +e?

**Comment by siniStar7boy** [comment] 2016-01-26 23:59
@Casey952 As of the latest git, Xtheme will add +e automatically to channel Founders upon registration.  Any channels previously registered before this commit will require +e being manually added to affected Founders.  

I'm not sure what you are saying about the templates now -- if you do not have owner/protect/halfop modules loaded, just remove the flags they would distribute from Xtheme.conf. (This is normal preparation/configuration)

I would not recommend editing services.db by hand in any circumstance.  

This issue is now fixed, so I am going to close the issue unless you have any additional bugs to report regarding this issue.

**Comment by Casey952** [comment] 2016-01-27 02:58
When you load/unload owner/protect/halfop, services.db automatically adds or removes +ahq to anyone who has those channel flags.

When you do not have them loaded and have +ahq in the ChanServ templates block in the conf, it does not use +ahq from the templates and ignores them if they are there.

When doing /msg ChanServ templates - the network templates do not use +ahq from the conf and displays the templates without +ahq and AOP shows as +AOeiorv / etc etc and will display as AOP as the name for flags and access list.

**Comment by siniStar7boy** [comment] 2016-01-27 03:03
As intended.. 

**Locking this issue** as it is _fixed_ as mentioned above.  

_Thanks for your interest in Xtheme and helping to make it better for everyone!_
