### ISSUE TITLE
services conf ircop operclass - needoper

### ISSUE THREAD

**Issue by Casey952** [XthemeOrg/Xtheme#63] opened 2016-11-05 08:09 UTC
I was thinking with the services conf ircop operclass, it does not have needoper - to maybe set it as needoper

```
operclass "ircop" {
	privs {
		special:ircop;
	};

	privs {
		user:auspex;
		user:admin;
		user:sendpass;
		user:vhost;
		user:mark;
	};

	privs {
		chan:auspex;
		chan:admin;
		chan:cmodes;
		chan:joinstaffonly;
	};

	privs {
		general:auspex;
		general:helper;
		general:viewprivs;
		general:flood;
	};

	privs {
		operserv:omode;
		operserv:akill;
		operserv:jupe;
		operserv:global;
	};

	privs {
		group:auspex;
		group:admin;
	};
};

operclass "sra" {
	/* You can inherit privileges from a lower operclass. */
	extends "ircop";

	privs {
		user:hold;
		user:regnolimit;
	};

	privs {
		general:metadata;
		general:admin;
	};

	privs {
		#operserv:massakill;
		#operserv:akill-anymask;
		operserv:noop;
		operserv:grant;
		#operserv:override;
	};

	/* needoper
	 * Only grant privileges to IRC users in this oper class if they
	 * are opered; other use of privilege (channel succession, XMLRPC,
	 * etc.) is unaffected by this.
	 */
	needoper;
};
```

**Comment by siniStar7boy** [comment] 2016-11-09 00:19
@Casey952 You can add `needoper;` to any oper class in the config to make it require the staff member be oper'd.   Closing as this is not a bug and functionality is already able to be assigned to any oper class.

**Comment by Casey952** [comment] 2016-11-09 00:53
was thinking if needoper could be included in `xtheme.conf.example` for the ircop operclass as it does not have it included.

no worries.

**Comment by siniStar7boy** [comment] 2016-11-09 01:19
Ah, this is a possibility.  Otherwise, it could just be documented better.  I will re-open and look into for final 7.5.0.

**Closed** 2016-11-09 17:34 UTC
Labels: enhancement, priority:Low
